services:
  postgres:
    image: postgres:16.1-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=hiddensc
      - POSTGRES_DB=mata_db
    ports:
      - 6500:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine3.18
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a cachesc ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 9990:6379
    volumes:
      - ./data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEPLOY=PRODUCT
    depends_on:
      - postgres
      - redis
      - jaeger
    restart: on-failure
    ports:
      - "8080:8080"

  jaeger:
    image: jaegertracing/all-in-one:1.53
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686   # query serve frontend (Jaeger UI)
      - 4318:4318     # OTLP collector http
      - 14268:14268   # collector accept jaeger.thrift directly from clients
      - 14269:14269

volumes:
  postgres:
