services:
  postgres:
    image: postgres:16.1-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=hiddensc
      - POSTGRES_DB=mata_db
    ports:
      - 6500:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
