// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Api struct {
	ID int64 `json:"id"`
	// public keys from 3rd API
	Key        string    `json:"key"`
	UsageCount int64     `json:"usage_count"`
	CreatedAt  time.Time `json:"created_at"`
}
