// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateAPI(ctx context.Context, key string) (Api, error)
	GetAPI(ctx context.Context) (Api, error)
	UpdateAPIUsageCount(ctx context.Context, arg UpdateAPIUsageCountParams) error
}

var _ Querier = (*Queries)(nil)
