---
http:
  address: 0.0.0.0
  port: 8080
api:
  # Key Get from IFramely Account, more info: https://iframely.com/docs/allow-origins#public-client-access
  key:
    - "key1"
    - "key2"
db:
  source: "postgresql://root:hiddensc@localhost:6500/mata_db?sslmode=disable"