---
http:
  address: 0.0.0.0
  port: 8080
api:
  # Key Get from IFramely Account, more info: https://iframely.com/docs/allow-origins#public-client-access
  # Example
  key:
    - "1972f55e8418132ff533420567c0e4c2"
    - "6f620ba1768066988d35bdcde3064460"
db:
  source: "postgresql://root:hiddensc@localhost:6500/mata_db?sslmode=disable"
cache:
  source: "redis://root:cachesc@localhost:9990/5?protocol=3"
  age: 3

migration_url: file://internal/db/migration